Repository National-Digital-Twin/LISA, pull requests merged in 2025-08, with the labels that each got.

#260 feat(DPAV-1430): new notifications page
  frontend/src/components/AppWrapper.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/Notifications/NotificationContent.tsx
  frontend/src/components/Notifications/NotificationItem.tsx
  frontend/src/components/Notifications/handlers.tsx
  frontend/src/components/NotificationsBanner.tsx
  frontend/src/components/NotificationsMenu/NotificationsMenu.tsx
  frontend/src/components/NotificationsMenu/__tests__/NotificationsMenu.test.tsx
  frontend/src/components/NotificationsMenu/index.ts
  frontend/src/components/__tests__/Header.test.tsx
  frontend/src/components/index.ts
  frontend/src/pages/Notifications.tsx
  frontend/src/pages/__tests__/Notifications.test.tsx
  frontend/src/utils/Document/__tests__/getBlobHash.test.ts
  frontend/src/utils/Format/__tests__/time.test.ts
  frontend/src/utils/Format/index.ts
  frontend/src/utils/Format/time.ts
Labels: feature

#270 feat(DPAV-1432) Placeholder home page
  frontend/src/components/AppWrapper.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/PageWrapper/PageWrapper.tsx
  frontend/src/components/Widgets/AlertsWidget.tsx
  frontend/src/components/Widgets/IntroWidget.tsx
  frontend/src/components/Widgets/TaskWidget.tsx
  frontend/src/components/Widgets/WidgetBase.tsx
  frontend/src/components/__tests__/Widgets/AlertsWidget.test.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/Incidents.tsx
Labels: feature

#272 feat(DPAV-1433): new burger menu for mobile
  frontend/src/assets/images/lisa_logo.svg
  frontend/src/assets/images/lisa_logo_mobile.svg
  frontend/src/assets/sass/_layout.scss
  frontend/src/components/AppWrapper.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/Layout.tsx
  frontend/src/components/PageWrapper/PageWrapper.tsx
  frontend/src/components/SideNavigation.tsx
  frontend/src/components/__tests__/Header.test.tsx
  frontend/src/components/__tests__/SideNavigation.test.tsx
  frontend/src/hooks/__tests__/useNavigation.test.tsx
  frontend/src/hooks/useNavigation.ts
  frontend/src/pages/Home.tsx
  frontend/src/pages/Incidents.tsx
Labels: feature

#277 feat(DPAV-1146): add further settings options and user profile base page
  frontend/src/components/AppWrapper.tsx
  frontend/src/components/Header.tsx
  frontend/src/pages/MyProfile.tsx
  frontend/src/pages/Settings.tsx
Labels: feature

#279 feat(DPAV-1436) Incident logbook screen redesign
  frontend/src/components/PageTitle.tsx
  frontend/src/components/Stage/StageMini.tsx
  frontend/src/pages/Logbook.tsx
Labels: feature

#288 feat(DPAV-1447): add tests and styling fix for names in user list
  frontend/src/pages/AdminUserList.tsx
  frontend/src/pages/__tests__/AdminNewUser.test.tsx
  frontend/src/pages/__tests__/AdminUserList.test.tsx
  frontend/src/pages/__tests__/AdminViewUser.test.tsx
  frontend/src/pages/__tests__/MyProfile.test.tsx
  frontend/src/pages/__tests__/Notifications.test.tsx
  frontend/src/setupTests.ts
Labels: feature

#286 feat(DPAV-1444): Add incident picker
  frontend/src/components/AppWrapper.tsx
  frontend/src/components/IncidentPicker.tsx
  frontend/src/pages/IncidentPickerPage.tsx
  frontend/src/pages/Tasks.tsx
Labels: feature

#291 feat(DPAV-1436) Sort/Filter chip count includes nested selections
  deployment/sag/Dockerfile
  deployment/sag/config/config.ttl
  frontend/src/components/SortFilter/SortAndFilter.tsx
  frontend/src/components/SortFilter/__tests__/filter-utils.test.ts
  frontend/src/components/SortFilter/filter-utils.ts
  frontend/src/utils/Document/getBlobHash.ts
Labels: feature

#295 bugfix(DPAV-1432) Fix task counts on home page
  frontend/src/components/Widgets/TaskWidget.tsx
  frontend/src/components/__tests__/Widgets/TaskWidget.test.tsx
Labels: fix

#297 bugfix(NON-REQ): add unit tests to CI pipeline and patch dependencies
  .github/workflows/backend-ci-pr.yml
  .github/workflows/frontend-ci-pr.yml
  backend/eslint.config.mjs
  backend/package.json
  backend/src/auth/middleware.ts
  backend/src/cjs-shim.ts
  backend/src/errors.ts
  backend/src/pubSub/manager.ts
  backend/src/services/auth.ts
  backend/src/services/logEntry/utils/mentions/reconcileFileMentions.ts
  backend/src/services/scg_demo.ts
  common/Fields/ContactName.ts
  common/eslint.config.mjs
  common/package.json
  frontend/eslint.config.mjs
  frontend/package.json
  frontend/qa/package.json
  frontend/qa/src/helper/report/init.ts
  frontend/qa/src/helper/wrapper/assert.ts
  frontend/qa/src/helper/wrapper/runLighthouse.ts
  frontend/qa/src/hooks/hooks.ts
  frontend/qa/src/pages/editIncidentLogPage.ts
  frontend/qa/src/test/steps/editIncidentSteps.ts
  frontend/src/api/ws.ts
  frontend/src/components/AddEntry/Location/LocationContent.tsx
  frontend/src/components/CustomForms/FormTemplates/SortableFieldRow.tsx
  frontend/src/components/Form/FormHelpButton.tsx
  frontend/src/components/HelpGuidance.tsx
  frontend/src/components/Map/MapComponent.tsx
  frontend/src/components/Map/SearchLocation.tsx
  frontend/src/components/SelectField.tsx
  frontend/src/components/Sketch.tsx
  frontend/src/components/Stage/__tests__/__snapshots__/StageComponent.test.tsx.snap
  frontend/src/components/lexical/plugins/ActionsPlugin.tsx
  frontend/src/components/lexical/plugins/nodes/MentionNode.ts
  frontend/src/hooks/__tests__/useAttachments.test.tsx
  frontend/src/hooks/useIncidents.ts
  frontend/src/hooks/useLogEntriesUpdates.tsx
  frontend/src/hooks/useMessaging.ts
  frontend/src/hooks/useNotifications.ts
  frontend/src/main.tsx
  frontend/src/pages/Notifications.tsx
  frontend/src/utils/Document/dataUrlToFile.ts
  frontend/src/utils/Format/__tests__/date.test.ts
  frontend/src/utils/Format/__tests__/dateAndTimeMobile.test.ts
  frontend/src/utils/__tests__/logger.test.ts
  frontend/src/utils/logger.ts
  frontend/vite.config.ts
  package-lock.json
  package.json
Labels: fix, actions

#300 feat(DPAV-1444): implement create task
  backend/.env-local
  backend/src/routes/index.ts
  backend/src/services/common/attachments.ts
  backend/src/services/common/location.ts
  backend/src/services/fileStorage.ts
  backend/src/services/incident.ts
  backend/src/services/logEntry/create.ts
  backend/src/services/logEntry/get.ts
  backend/src/services/logEntry/utils/attachments/parseAttachments.ts
  backend/src/services/logEntry/utils/index.ts
  backend/src/services/task/create.ts
  backend/src/services/task/get.ts
  backend/src/services/task/utils/select/attachments.ts
  backend/src/services/task/utils/select/index.ts
  backend/src/services/task/utils/select/tasks.ts
  backend/src/settings.ts
  common/Attachment.ts
  common/IncidentAttachment.ts
  common/LogEntry.ts
  common/Task.ts
  common/index.ts
  deployment/sag/docker-compose.yaml
  frontend/src/components/AddEntity/EntityOptions.tsx
  frontend/src/components/AddEntity/EntityOptionsContainer.tsx
  frontend/src/components/AddEntry/index.tsx
  frontend/src/components/AppWrapper.tsx
  frontend/src/components/AttachmentLink.tsx
  frontend/src/components/DataList.tsx
  frontend/src/components/EntryList/Attachments.tsx
  frontend/src/components/EntryList/__tests__/Task.test.tsx
  frontend/src/components/Task/TaskInputContainer.tsx
  frontend/src/hooks/index.ts
  frontend/src/hooks/useTaskUpdates.tsx
  frontend/src/hooks/useTasks.ts
  frontend/src/pages/CreateLogEntry.tsx
  frontend/src/pages/CreateTask.tsx
  frontend/src/pages/IncidentTasks.tsx
  frontend/src/pages/Tasks.tsx
  frontend/src/pages/__tests__/Tasks.test.tsx
  frontend/src/utils/Format/mentionable/attachment.ts
Labels: feature

#318 feature(NON-REQ): convert to unprivileged NGINX image
  Dockerfile.frontend
  deployment/k8s/transparent-proxy/base/deployment.yaml
  deployment/k8s/transparent-proxy/base/service.yaml
  deployment/k8s/webapp/base/deployment.yaml
  deployment/k8s/webapp/base/service.yaml
  transparent-proxy/Dockerfile
Labels: feature

#319 feat(DPAV-1572): Create log entry after task creation
  backend/src/services/logEntry/utils/details/extractDetails.ts
  backend/src/services/logEntry/utils/details/parseDetails.ts
  backend/src/services/logEntry/utils/select/details.ts
  common/LogEntryChangeDetails.ts
  common/LogEntryType.ts
  common/LogEntryTypes/TaskCreated.ts
  common/LogEntryTypes/index.ts
  frontend/src/components/EntryList/Details/TaskCreated.tsx
  frontend/src/components/EntryList/Details/index.tsx
  frontend/src/hooks/useTasks.ts
  frontend/src/pages/CreateTask.tsx
  frontend/src/utils/Task/updateLogEntries.ts
Labels: feature

#326 feat(DPAV-1434) Update incidents page to match designs
  frontend/src/pages/Incidents.tsx
  frontend/src/pages/Tasks.tsx
Labels: feature

#328 feat(DPAV-1444): update styling after designer testing
  frontend/src/components/AddEntity/EntityInputContainer.tsx
  frontend/src/components/AddEntity/EntityOptions.tsx
  frontend/src/components/AddEntity/EntityOptionsContainer.tsx
Labels: feature

#330 bugfix(NON-REQ): Task bug fixes
  frontend/src/components/Notifications/handlers.tsx
  frontend/src/pages/IncidentTask.tsx
Labels: fix

#331 feat(DPAV-1440): Add new task button from incident overview page
  frontend/src/pages/Logbook.tsx
Labels: feature

#332 fix(DPAV-1447): add no result content when users not matched to filters
  frontend/src/pages/AdminUserList.tsx
Labels: fix

#333 bugfix(NON-REQ): exclude inactive users from selects
  frontend/src/components/AddEntry/index.tsx
  frontend/src/components/Task/TaskInputContainer.tsx
  frontend/src/pages/AdminUserList.tsx
  frontend/src/pages/CreateLogEntry.tsx
  frontend/src/pages/IncidentTask.tsx
Labels: fix

#335 feat(DPAV-1432): setup Add New button on summary page
  frontend/src/hooks/index.ts
  frontend/src/hooks/useMenu.ts
  frontend/src/pages/Home.tsx
  frontend/src/pages/Logbook.tsx
Labels: feature

#337 fix(NON-REQ) Redirect to login after 403/401 on ping
  frontend/src/main.tsx
  frontend/src/providers/OnlineProvider.tsx
  frontend/src/utils/authRedirect.ts
Labels: fix

#343 bugifx(NON-REQ) Revert "Merge pull request #337 from National-Digital-Twin/bugfix/403…
  frontend/src/main.tsx
  frontend/src/providers/OnlineProvider.tsx
  frontend/src/utils/authRedirect.ts
Labels: fix

#344 feat(NON-REQ) Inline selectors should be wider
  frontend/src/components/InlineSelectors/BaseInlineSelector.tsx
Labels: feature

#345 feat(NON-REQ) Add Release to Staging workflow back
  .github/workflows/gitflow-release.yaml
Labels: feature

#346 feat(DPAV-1430): add seen state to notifications and improve cache management
  .github/PULL_REQUEST_TEMPLATE.md
  backend/src/routes/index.ts
  backend/src/services/notifications/index.ts
  backend/src/services/notifications/types.ts
  backend/src/services/notifications/utils.ts
  common/Notification.ts
  frontend/src/App.tsx
  frontend/src/components/Header.tsx
  frontend/src/context/NotificationContext.tsx
  frontend/src/hooks/__tests__/notification.mock.ts
  frontend/src/hooks/__tests__/pollForReadNotifications.test.tsx
  frontend/src/hooks/__tests__/pollForTotalNotifications.test.tsx
  frontend/src/hooks/__tests__/useNotifications.test.tsx
  frontend/src/hooks/index.ts
  frontend/src/hooks/useNotificationContext.ts
  frontend/src/hooks/useNotifications.ts
  frontend/src/pages/Notifications.tsx
  frontend/src/pages/__tests__/Notifications.test.tsx
  frontend/src/providers/NotificationProvider.tsx
  frontend/src/providers/__tests__/NotificationProvider.test.tsx
Labels: documentation, feature

#350 feat(dpav-1441): added support for risk assessment form
  Makefile
  common/Field.ts
  common/Fields/CommunicationMethod.ts
  common/Fields/ContactName.ts
  common/LogEntryTypes/RiskAssessment/hazards/Handling.ts
  common/LogEntryTypes/RiskAssessment/hazards/RelevantHazard.ts
  common/LogEntryTypes/RiskAssessment/hazards/index.ts
  common/LogEntryTypes/RiskAssessment/hazards/utils.ts
  common/LogEntryTypes/RiskAssessment/index.ts
  common/eslint.config.mjs
  frontend/src/components/AddEntity/EntityOption.tsx
  frontend/src/components/AddEntity/EntityOptions.tsx
  frontend/src/components/CustomForms/FormInstances/FormContainer.tsx
  frontend/src/components/CustomForms/FormInstances/UiWidgets.tsx
  frontend/src/components/Form/FormsInputContainer.tsx
  frontend/src/components/Task/TaskInputContainer.tsx
  frontend/src/hooks/useLogEntries.ts
  frontend/src/hooks/useTasks.ts
  frontend/src/utils/Form/getFieldIcon.tsx
  frontend/src/utils/Task/updateLogEntries.ts
  schema/Hazards/hazards-data-schema.json
  schema/Hazards/hazards-ui-schema.json
  schema/Hazards/hazards.ttl
  schema/SitRep/siteRep-data-schema.json
Labels: feature

#352 feat(dpav-1441): added support for risk assessment review form
  frontend/eslint.config.mjs
  frontend/src/components/AddEntity/EntityOptions.tsx
  frontend/src/components/Form/FormsInputContainer.tsx
Labels: feature
